name: "DoViRemux"
guid: "2f215b63-1a73-4193-9102-78f84d027014"
version: 2.0.2
targetAbi: "10.10.6.0"
framework: "net8.0"
owner: "katiekloss"
overview: "Automatically remux Dolby Vision 8.1 files"
description: >
  Remuxes media with Dolby Vision profile 8.1 metadata from MKV to MP4, for better support on LG WebOS TVs.

category: "General"
artifacts:
  - "Jellyfin.Plugin.DoViRemux.dll"
changelog: |-
  - Fixed PluginConfiguration.OnlyRemuxLibraries/IncludeAncestorIds when it's empty
